import Head from 'next/head';
import { Heading, FormTest, Rating } from 'components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Eco Shop</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <Heading type='filter' text='drieD frUiTs' />
        <Rating type='full' score={3.3}/>
        <FormTest />
      </div>
    </>
  );
}
