import Head from 'next/head';
import styled from 'styled-components';

const Heading = styled.h1`
  color: #ffa600;
  font-family: ${({ theme }) => theme.fonts.heading};
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Eco Shop</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <Heading>Home</Heading>
      </div>
    </>
  );
}
